<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net462</TargetFrameworks>
    <Authors>Acadian Ambulance Service</Authors>
    <Description>
      F# utilities, including extra String, Seq, Option, and Result functions, option and result computation
      expressions, and a Parse module.
    </Description>
    <PackageProjectUrl>https://github.com/Acadian-Ambulance/Acadian.FSharp</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="Builders.fs" />
    <Compile Include="FSharp.fs" />
    <None Include="../LICENSE.txt" Pack="true" PackagePath="$(PackageLicenseFile)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="6.0.0" />
  </ItemGroup>
</Project>
